---
title: "J15221 Evanthia TNBC - Correlation TILs, CD8, FoxP3, TMB with response"
author: "Ludmila Danilova & Joseph Tandurella"
date: "`r Sys.Date()`"

output:
  html_document:
    toc: yes
    toc_float: yes

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE,
                      warning = FALSE)
rm(list = ls())

library(dplyr)
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(data.table)
library("DT")
library(pheatmap)
library(gridExtra)
library(scales)

##Create All Facet for plotting
CreateAllFacet <- function(df, col){
  df$facet <- df[[col]]
  temp <- df
  temp$facet <- "All"
  merged <-rbind(temp, df)

  # ensure the facet value is a factor
  merged[[col]] <- as.factor(merged[[col]])

  return(merged)
}


```

Create figures for the clinical paper

All data is coming from tables for the paper


```{r  fig.width = 10}
# labels for time points
timeLab  = c("Baseline", "Post Run-in", "Week 8")

# set colors
recistCol = c("Non-responder" = "red","Responder" = "blue")
cbrCol = c("CR,PR,SD" = "blue","PD" = "red")
subtypeCol = c("HR+" = "red", "TNBC" = "blue")
timeCol = setNames(c("black", 'grey45', 'grey75'), timeLab)

# set root folder
rootDir = "./"

# Load data patient data
dta_pts = read.csv(paste0(rootDir,"input_tables/table_patient_info.csv"), row.names = 1)
dta_pts$ID = rownames(dta_pts)

#==========================
# file with TILs and PDL1 data
dat = read.csv(paste0(rootDir,"input_tables/table_per_sample_values.csv"))


#===========================
# add patient info 
dat = cbind(dat,  dta_pts[dat$patientID,])

df_Baseline <- dat %>% filter(timePoint == 'Baseline')

df_sampInfo <- CreateAllFacet(dat, "Subtype")

```


## TILs 

```{r fig.width = 10}

##by type and RECIST
ggpaired(df_sampInfo %>% filter(!is.na(TILs)), x="timePoint",y="TILs", id = "patientID", line.color = "RECIST", line.size = 0.4,
 palette =  recistCol, title = "TILs. All Samples", xlab="Time", ylab="TILs") + 
  scale_x_discrete(labels=timeLab)+ 
  stat_compare_means(comparisons = list(c(timeLab[1],timeLab[2]), c(timeLab[1],timeLab[3]),c(timeLab[2],timeLab[3])))+ 
#  stat_compare_means(label.x=.85, label.y = 50 ) 
  facet_wrap("facet") 


```

## CD8 

```{r  fig.width = 10}
##by type and RECIST
ggpaired(df_sampInfo %>% filter(!is.na(CD8)), x="timePoint",y="CD8", id = "patientID", line.color = "RECIST", line.size = 0.4,
 palette =  recistCol, title = "CD8. All Samples", xlab="Time", ylab="CD8 Density") + 
  scale_x_discrete(labels=timeLab)+ 
  scale_y_continuous(trans = "log10") +
  stat_compare_means(comparisons = list(c(timeLab[1],timeLab[2]), c(timeLab[1],timeLab[3]),c(timeLab[2],timeLab[3])))+ 
  facet_wrap("facet") 

print("A summary table:")
# split by timePoint
dat1 = split(df_sampInfo, df_sampInfo$timePoint)
# get summary
tab = t(sapply(dat1, function(x) summary(x$CD8)))
print(tab)
tab = cbind(timePoint = rownames(tab), tab)


```

## FoxP3 

```{r  fig.width = 10}
##by type and RECIST
ggpaired(df_sampInfo %>% filter(!is.na(FOXP3)), x="timePoint",y="FOXP3", id = "patientID", line.color = "RECIST", line.size = 0.4,
 palette =  recistCol, title = "FOXP3. All Samples", xlab="Time", ylab="FOXP3 Density") + 
  scale_x_discrete(labels=timeLab)+ 
  scale_y_continuous(trans = "log10") +
  stat_compare_means(comparisons = list(c(timeLab[1],timeLab[2]), c(timeLab[1],timeLab[3]),c(timeLab[2],timeLab[3])))+ 
  facet_wrap("facet")  

```

## CD8/FoxP3 

```{r  fig.width = 10}
##by type and RECIST
ggpaired(df_sampInfo %>% filter(!is.na(ratio)), x="timePoint",y="ratio", id = "patientID", line.color = "RECIST", line.size = 0.4,
 palette =  recistCol, title = "CD8/FoxP3 ratio. All Samples", xlab="Time", ylab="CD8/FoxP3 ratio") + 
  scale_x_discrete(labels=timeLab)+ 
  scale_y_continuous(trans = "log2") +
  stat_compare_means(comparisons = list(c(timeLab[1],timeLab[2]), c(timeLab[1],timeLab[3]),c(timeLab[2],timeLab[3])))+ 
  facet_wrap("facet") 

```


## TMB

```{r  fig.width = 10}
print(summary(df_Baseline$TMB_perMB))


```
```{r}
sessionInfo()
```
