---
title: "J15221 Evanthia TNBC - Clinical efficacy, survival, ORR"
author: "L. Danilova, J. A. Tandurella, C. Wang"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE,
                      warning = FALSE)
rm(list = ls())

library(dplyr)
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(data.table)
library("DT")
library(gridExtra)
library(survival)
library(survminer)

source("functions.r")

```


```{r  fig.width = 10}
# set colors
recistCol = c("Non-responder" = "red","Responder" = "blue")
cbrCol = c("CR,PR,SD" = "blue","PD" = "red")
subtypeCol = c("HR+" = "red", "TNBC" = "blue")
timeCol = c("Baseline" = "black", "Time 1" = 'grey45', "Time 2" = 'grey75')

# set root folder
rootDir = "./"


# Load data patient data
dta_pts = read.csv(paste0(rootDir,"input_tables/table_24patient_info.csv"), row.names = 1)
dta_pts$ID = rownames(dta_pts)

# number of prior therapies by subtype
print("summary of the number of prior therapies by subtype")
print(aggregate(dta_pts$n_therapies, by = list(dta_pts$Subtype), FUN = summary))
t.test(dta_pts$n_therapies ~ dta_pts$Subtype)


# load data for a spider plot
dta_tumor = read.csv(paste0(rootDir,"input_tables/table_tumor_size_change.csv"))
colnames(dta_tumor) = c("ID",'Days', "Y" )

datatable(dta_pts)

```


# ORR and CBR
## 20 patients with evaulable response

```{r  fig.width = 10}
dta_pts_20 = dta_pts %>% filter(Best_Resp != "Unknown")

# get table with ORR for RECIST
tab1 = get_freq_table(dta_pts_20, "OR")
# get table with CBR for RECIST
tab2 = get_freq_table(dta_pts_20, "CB_6mth_yn")

# get table with ORR for irRECIST
tab3 = get_freq_table(dta_pts_20, "irOR")

print("ORR with RECIST")
datatable(tab1)
write.csv(tab1, file = "table_orr_RECIST.csv", row.names = F)

print("ORR with irRECIST")
datatable(tab3)
write.csv(tab1, file = "table_orr_irRECIST.csv", row.names = F)

print("CBR")
datatable(tab2)
write.csv(tab1, file = "table_orr_cbr.csv", row.names = F)

```

## Excluding dose level 4

```{r  fig.width = 10}
# get table with ORR for RECIST
tab1 = get_freq_table(dta_pts_20 %>% filter(Dose_level != 4), "OR")
# get table with CBR for RECIST
tab2 = get_freq_table(dta_pts_20%>% filter(Dose_level != 4), "CB_6mth_yn")

# get table with ORR for irRECIST
tab3 = get_freq_table(dta_pts_20%>% filter(Dose_level != 4), "irOR")

print("ORR with RECIST")
datatable(tab1)
write.csv(tab1, file = "table_orr_RECIST_noDose4.csv", row.names = F)

print("ORR with irRECIST")
datatable(tab3)
write.csv(tab1, file = "table_orr_irRECIST_noDose4.csv", row.names = F)

print("CBR")
datatable(tab2)
write.csv(tab1, file = "table_orr_cbr_noDose4.csv", row.names = F)

```

# Best response


```{r  fig.width = 7}


#=========================================
# # waterfall plot of Best Overall Response (%)

# adds patient info to tumor data
dat <- get_tumor_best(dta_tumor) %>%
        left_join(dta_pts)

# reproducing waterfall plot of best response
wtr1 = ggplot(dat, aes(x = reorder(ID, -Y), y = Y, fill = Subtype)) +
  ylab ("Best Overall Response (%)") +
  xlab("Patients") +
  geom_bar(stat = "identity") + ylim(-100, 100) +
  scale_fill_manual(values = subtypeCol) +
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  geom_hline(yintercept = c(-30, 20), linetype = 'dashed') +
  geom_text(aes(y=1, label = exceptional_response), size = 6)

print(wtr1)
#===============
# waterfall of months
#==============
dat <- get_tumor_best(dta_tumor) %>%
        left_join(dta_pts) %>%
        mutate(Days = Days / 30.5) %>% # convert days to months
        arrange(Subtype, Days)
# make ID as factor with order organized by type and days. 
# otherwise, barplot makes it in alphabetical order
dat$ID = factor(dat$ID, levels = dat$ID)

wtr2 = ggplot(dat, aes(x = Days, y = ID, fill = Subtype)) +
  ylab("Patients") +
  geom_bar(stat = "identity") +
  theme_bw()+
  labs(x = "Months")+
  scale_fill_manual(values = subtypeCol) +
  geom_text(aes(y=ID, x = Days + 1, label = exceptional_response), size = 6)

print(wtr2)

#====================
# spider plot
#====================
  # keep only sample from patients with patient info
dta_tumor <- dta_tumor %>% filter(ID %in% dta_pts$ID)
    # add patient into to tumor data
    dat <- dta_tumor %>%
        left_join(dta_pts) %>%
        mutate(Days = Days / 30.5,
               Y    = Y *  100) %>%
        arrange(ID, Days)
    # add stars
    dta_star <- dat %>%
        filter(exceptional_response == "*") %>%
        group_by(ID) %>%
        filter(Days == max(Days)) %>%
        mutate(Days = Days,
               label = "*") %>% 
        rbind(dat %>%
        filter(exceptional_response == "**") %>%
        group_by(ID) %>%
        filter(Days == max(Days)) %>%
        mutate(Days = Days,
               label = "**"))
    # make plot
sp1 = ggplot(data = dat, aes(x = Days, y = Y)) +
        geom_line(aes(group = ID, col = Subtype), size = 1.5) +
        theme_bw() +
        labs(x = "Months", y = "Percent Change") +
        geom_hline(yintercept = 0) +
        geom_hline(yintercept = 30,  lty = 2) +
        geom_hline(yintercept = -30, lty = 2) +
        scale_colour_manual(values = subtypeCol) +
        geom_text(data = dta_star,
                  aes(x = Days, y = Y+1, label = label),size = 6)+
  theme(legend.title = element_blank(), legend.position = c(0.5, 0.88))

print(sp1)


```


# Survival analysis

```{r fig.height= 8}

## -------------------------------------------------------------
##            Survival
## -------------------------------------------------------------


pfs <- plot_surv(dta_pts_20, "PFS", "Progression Free Survival", x_6m = 12, xlim = 50, xtext = 35, add6m = T)

os <- plot_surv(dta_pts_20, "OS", "Overall Survival", x_6m = 15, x_12 = 20, add6m = T)

pfs <- plot_surv(dta_pts, "PFS", "Progression Free Survival", x_6m = 12, xlim = 50, xtext = 35)

os <- plot_surv(dta_pts, "OS", "Overall Survival", x_6m = 15, x_12 = 20)

```

```{r}
sessionInfo()
```