---
title: "J15221 Evanthia TNBC - Correlation PD-L1 with response"
author: "Ludmila Danilova & Joseph Tandurella"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE,
                      warning = FALSE)
rm(list = ls())

library(dplyr)
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(data.table)
library("DT")
library(pheatmap)
library(gridExtra)
library(scales)

##Create All Facet for plotting
CreateAllFacet <- function(df, col){
  df$facet <- df[[col]]
  temp <- df
  temp$facet <- "All"
  merged <-rbind(temp, df)

  # ensure the facet value is a factor
  merged[[col]] <- as.factor(merged[[col]])

  return(merged)
}


```

Create figures for the clinical paper

All data is coming from tables for the paper


```{r  fig.width = 10}
# set colors
recistCol = c("Non-responder" = "red","Responder" = "blue")
cbrCol = c("CR,PR,SD" = "blue","PD" = "red")
subtypeCol = c("HR+" = "red", "TNBC" = "blue")
timeCol = c("Baseline" = "black", "Time 1" = 'grey45', "Time 2" = 'grey75')

# set root folder
rootDir = "./"

# Load data patient data
dta_pts = read.csv(paste0(rootDir,"input_tables/table_24patient_info.csv"), row.names = 1)
dta_pts$ID = rownames(dta_pts)

# remove patients with no response
dta_pts = dta_pts %>% filter(Best_Resp != "Unknown")

#==========================
# file with TILs and PDL1 data
dat = read.csv(paste0(rootDir,"input_tables/table_per_sample_values.csv"))


#===========================
# add patient info 
dat = cbind(dat,  dta_pts[dat$patientID,])

df_Baseline <- dat %>% filter(timePoint == 'Baseline')

```


## PD-L1 split by type

### Cancer cells

```{r fig.width = 10}

#================
# PD-L1

##RECIST (Responders vs. Nonresponders)
ggplot(CreateAllFacet(df_Baseline, "Subtype"), aes(x=RECIST, y=PDL1_tumor)) + 
  geom_boxplot() + 
  labs(title="% of PD-L1+ cancer cells. Baseline Samples") + 
  stat_compare_means() + 
  geom_point(aes(color=Subtype)) + 
  scale_y_log10()+
  scale_color_manual(values = subtypeCol) +
  geom_hline(yintercept=1, linetype="dashed", color = "grey") +
  facet_wrap("facet")+ 
  theme_bw()


```


### Immune cells

```{r  fig.width = 10}

##RECIST (Responders vs. Nonresponders)
ggplot(CreateAllFacet(df_Baseline, "Subtype"), aes(x=RECIST, y=PDL1_immune)) + 
  geom_boxplot() + 
  labs(title="% of PD-L1+ immune cells. Baseline Samples") + 
  stat_compare_means() + 
  geom_point(aes(color=Subtype)) + 
  scale_y_log10()+
  scale_color_manual(values = subtypeCol) +
  geom_hline(yintercept=1, linetype="dashed", color = "grey") +
  facet_wrap("facet")+ 
  theme_bw()

```

```{r}
sessionInfo()
```


